//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BAKIYE
    {
        public string MUSTERIID { get; set; }
        public long BAKIYE { get; set; }
    
        public virtual TBL_MUSTERI TBL_MUSTERI { get; set; }
    }
}
